spring:
  profile:
     active:
     - dev
---
spring:
  profile: dev #开发环境
  application:
      name: microsevercloud-cofig-ldg-dev
---
spring:
  profile: dev #测试环境
  application:
      name: microsevercloud-cofig-ldg-test