spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
    application:
      name: microsevercloud-cofig-ldg-dev
---
spring:
  profiles: test
    application:
      name: microsevercloud-cofig-ldg-test